### ISSUE TITLE
use proxy to download

### ISSUE THREAD

**Issue by yysijie** [hellock/icrawler#1]
I hope icrawler can support proxy service with flexible strategies as soon as possible. I think it's useful in many applications. 

By the way, icrawler is really an excellent image crawler framework with multi-thread and higher extendibility. And the code has been well commented. 

This framework greatly reduce my workload. Thx a lot.

**Comment by hellock** [comment]
Of course this is useful, the support for custom proxies and proxy pool is on the go. As soon as the branch [proxy-pool](https://github.com/hellock/icrawler/tree/proxy-pool) is ok, I will merge it into the master branch.
Glad that icrawler can help you and welcome for PRs.

**Comment by hellock** [comment]
You can use proxies to crawl pages now. Two classes are added: `ProxyPool` and `ProxyScanner`.

**Comment by yysijie** [comment]
Thank you. 
Now I can play some dirty tricks.
