### ISSUE TITLE
ERROR - downloader - Response status code 404

### ISSUE THREAD

**Issue by johny322** [hellock/icrawler#100]
Hi. I tried to use your library. I encountered that no file is downloaded because of the Response Status Code 403 or 404 or an Exception Caught When Downloading File appears.
I use an example from the documentation, but I also don't get anything.
Examples of logs:
ERROR - downloader - Response status code 404, file https://pxhere.com/en/photo/1522983"
ERROR - downloader - Response status code 403, file https://www.pexels.com/photo/orange-tabby-cat-1769642/"
ERROR - downloader - Exception caught when downloading file https://www.army.mil/article/240653/one_health_week_pet_safety_during_the_holidays"

**Comment by nguyenkaos** [comment]
same probleme, since a week, I can't download any image

**Comment by theblackfly** [comment]
Same issue since a week.

**Comment by ayomi-devteam** [comment]
please help ... I have same problem ...

**Comment by ZhiyuanChen** [comment]
Could you please try to install from source and see if the error still exist?

**Comment by theblackfly** [comment]
> Could you please try to install from source and see if the error still exist?

Installing from source fixes the issue for me.

**Comment by ZhiyuanChen** [comment]
Fixed in #102 and release 0.6.5, thank you guys!
