### ISSUE TITLE
Minimal example not working

### ISSUE THREAD

**Issue by guillaume-safi** [hellock/icrawler#127]
I ran the minimal example, all seems to run normally, but I get no images. 

![image](https://github.com/hellock/icrawler/assets/146853227/a58081a7-a99c-4d89-a350-100423500cf4)

I tried changing the root_dir to files that exist and still no images are downloaded:

![image](https://github.com/hellock/icrawler/assets/146853227/fe2d2e24-2d4d-4874-9d1f-4e871bed9460)

* I am running version 0.6.8
* ubuntu 22.04

**Comment by theVerySharpFlat** [comment]
I get the same issue

**Comment by roper26** [comment]
same

**Comment by ZhiyuanChen** [comment]
This should have been fix in v0.6.9, could you please confirm if its resolved
