### ISSUE TITLE
Parser kwargs no accepted

### ISSUE THREAD

**Issue by ed2050** [hellock/icrawler#128]
The Crawler class takes a classname for the parser class, and a dict of parser_args to instantiate the parser:
```py
class Crawler:
    def __init__(
        ...
        parser_cls=Parser,
        extra_parser_args=None,
        ...
    ):
        ...
        parser_kwargs = {} if extra_parser_args is None else extra_parser_args
        self.parser = parser_cls(parser_threads, self.signal, self.session, **parser_kwargs)
```

Yet the parser class doens't accept any kwargs.  It's constructor is:
```
class Parser(ThreadPool):
    def __init__(self, thread_num, signal, session):
```

Why is this the case?  It causes problems when passing extra kwargs.  For example

**Comment by ZhiyuanChen** [comment]
Please let me know if https://github.com/hellock/icrawler/commit/42730647da9b80f02562603137e346050dd5fa4e can fix your issue
