### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sysu18364004** [hellock/icrawler#129]
How to solve the following question: 
ImportError: cannot import name 'storage' from partially initialized module 'icrawler' (most likely due to a circular import) (/mnt/data/***/miniconda3/envs/dl_daily/lib/python3.10/site-packages/icrawler-0.0.0-py3.10.egg/icrawler/__init__.py)

**Comment by ZhiyuanChen** [comment]
Can you provide a minimum working example?
