### ISSUE TITLE
save meta data on the images from crawler

### ISSUE THREAD

**Issue by oak-tree** [hellock/icrawler#14]
Hello is it possible to save `meta data` like mapping `image url` to `filename` for later use and to save license type as well?

**Comment by hellock** [comment]
Yes, you can processe meta data by overriding two methods: [`downloader.process_meta(task)`](https://github.com/hellock/icrawler/blob/master/icrawler/downloader.py#L134) and [`parser.parse()`](https://github.com/hellock/icrawler/blob/master/icrawler/parser.py#L37), or `parse` method of specific crawlers.
First, you can put meta data into the `task` dict besides the `file_url` field, and then process meta data in `process_meta` method, which by default does nothing.

**Comment by oak-tree** [comment]
so if I want to append some meta data to file i should do it at `process_meta`? 


I also want to save the original `url` and the name of the new file in a file, where should I put these code?

thanks again

**Comment by hellock** [comment]
If you want to save the original url, you can simply do it in `process_meta`, but for the filename, you need to put the filename to the `task` dict first, and this should be done at the end of `downloader.download` method.
The only parameter of `process_meta` is `task`, so all the meta data should be added into `task` before it can be accessed in `process_meta`.

**Comment by oak-tree** [comment]
Can I update the `task` at the  `get_filename` ?

Does `process_meta` is being called after it?

**Comment by hellock** [comment]
Yes you are right.

**Comment by oak-tree** [comment]
thanks, do you happen to know if incoming data holds the `image license`  as well? I cannot find any document on that subject in google docs

**Comment by hellock** [comment]
I am afraid that it may be hard to find all images' license. The google image search results do not provide such info.

**Comment by oak-tree** [comment]
ha, thanks for the information anyhow

**Comment by DeepVoltaire** [comment]
@oak-tree I am also interested in saving the urls, have you managed to solve it and can provide some code? Thanks!

**Comment by iPlugin** [comment]
> @oak-tree I am also interested in saving the urls, have you managed to solve it and can provide some code? Thanks!

Do you get feedback about code?
