### ISSUE TITLE
setup prefix for file

### ISSUE THREAD

**Issue by oak-tree** [hellock/icrawler#15]
Hello, is it possible to setup a prefix for the files generates by the `google\bing\flicker` downloder?

for example file can start `google_0001.jpg` or something like that 

thanks

**Comment by hellock** [comment]
Yes it is supported, you can just overriding the function [`downloader.get_filename`](https://github.com/hellock/icrawler/blob/master/icrawler/downloader.py#L61), which generates filename for saving images.

**Comment by oak-tree** [comment]
so If I get it right I should override both `ImageDownloader` and `Downloader` in order to override the `get_file` in parent and supply the `child` the new implementation?

**Comment by hellock** [comment]
You only need to override the subclasses. For example if you want all images by crawled by `GoogleImageCrawler` to be named "google_xxxxx.jpg", you can just override `GoogleImageCrawler.get_filename` like the following:
```python
class MyGoogleCrawler(GoogleImageCrawler):
    def get_filename(self, task, default_ext):
        return 'google_' + super(MyGoogleCrawler, self).get_filename(task, default_ext)
```

**Comment by oak-tree** [comment]
Doesn't `GoogleImageCrawler` is the child of `Crawler`? If so
GoogleImageCrawler
it self does not own the `get_filename` method isn't?

**Comment by hellock** [comment]
A child class will inherit methods from its parents so `GoogleImageCrawler` owns the `get_filename` method.

**Comment by oak-tree** [comment]
but crawler is not a child of `Downloader` isnt?

**Comment by hellock** [comment]
Sorry that I mixed the downloader with crawler. You can do it this way.
```python
class GoogleDownloader(ImageDownloader):
    def get_filename(self, task, default_ext):
        return 'google_' + super(ImageDownloader, self).get_filename(task, default_ext)

class MyGoogleCrawler(GoogleImageCrawler):
    def __init__(self, *args, **kwargs):
        Crawler.__init__(
            self,
            feeder_cls=GoogleFeeder,
            parser_cls=GoogleParser,
            downloader_cls=GoogleDownloader,
            *args,
            **kwargs)
```

**Comment by hellock** [comment]
#34
