### ISSUE TITLE
How doea the cache machinsim work?

### ISSUE THREAD

**Issue by oak-tree** [hellock/icrawler#17]
In case of exception and rerunning the crawler
1. Does it cache the `html` page?
1. Does it cache the parsed `html`?
1. Does it cache the image urlist?

thanks

**Comment by hellock** [comment]
Currently this feature is not implemented.
Crawled page urls and image urls are only available in memory during runtime. Dumping them to hard disk and resuming from them the next time is a good idea but not added now.

**Comment by oak-tree** [comment]
thanks for the information.
