### ISSUE TITLE
downloader-04 is waiting for new download tasks

### ISSUE THREAD

**Issue by unluckydan** [hellock/icrawler#2]
I really like your crawler! However, I don't know what's kind of problem about it. Maybe you can add a time constraint for feeder or something else.

**Comment by hellock** [comment]
Glad that you like it, are you using built-in crawlers? Could you provide some more info or logs about the problem?
In fact, when making requests or getting tasks from the queue, the argument `timeout` is usually set, maybe you are not using the lastest version?

**Comment by unluckydan** [comment]
I am sorry to trouble you. Maybe I just used pip to install your toolkit so
the version is too old. The latest version is working very well thanks for
your contribution for my work.^^

2016-04-20 0:46 GMT+08:00 Kai Chen <notifications@github.com>:

> Glad that you like it, are you using built-in crawlers? Could you provide
> some more info or logs about the problem?
> In fact, when making requests or getting tasks from the queue, the
> argument timeout is usually set, maybe you are not using the lastest
> version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hellock/icrawler/issues/2#issuecomment-212011577>
>



-- 
Hao Zhu
NeuroImage Computation Lab
Institute of Cognitive Neuroscience & Learning
Beijing Normal University

**Comment by unluckydan** [comment]
it is still waiting for downloader......... Maybe because I am in china and
the great fireware let it down? I have no idea about it.

2016-04-20 11:38 GMT+08:00 unluckydan.bnu <unluckydan.bnu@gmail.com>:

> I am sorry to trouble you. Maybe I just used pip to install your toolkit
> so the version is too old. The latest version is working very well thanks
> for your contribution for my work.^^
>
> 2016-04-20 0:46 GMT+08:00 Kai Chen <notifications@github.com>:
>
>> Glad that you like it, are you using built-in crawlers? Could you provide
>> some more info or logs about the problem?
>> In fact, when making requests or getting tasks from the queue, the
>> argument timeout is usually set, maybe you are not using the lastest
>> version?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hellock/icrawler/issues/2#issuecomment-212011577>
>>
>
>
>
> --
> Hao Zhu
> NeuroImage Computation Lab
> Institute of Cognitive Neuroscience & Learning
> Beijing Normal University
>



-- 
Hao Zhu
NeuroImage Computation Lab
Institute of Cognitive Neuroscience & Learning
Beijing Normal University

**Comment by hellock** [comment]
What crawler are you using and which site are you crawling, maybe I can figure it out with more info.

**Comment by unluckydan** [comment]
just bing. I want to crawl photos from bing, I gave the name, and got
photos from your crawls (e.g. jennifer lawrence and someone like this)

2016-04-20 18:54 GMT+08:00 Kai Chen <notifications@github.com>:

> What crawler are you using and which site are you crawling, maybe I can
> figure it out with more info.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hellock/icrawler/issues/2#issuecomment-212379055>
>



-- 
Hao Zhu
NeuroImage Computation Lab
Institute of Cognitive Neuroscience & Learning
Beijing Normal University

**Comment by hellock** [comment]
I found the cause of this problem and fixed the bug. Thanks for your information.
