### ISSUE TITLE
Is the date range inclusive or exclusive?

### ISSUE THREAD

**Issue by bryanyzhu** [hellock/icrawler#20]
Hi, thanks for the awesome code. I am using it to download google images and it works perfectly. I just have a question, is the date range inclusive or exclusive? 

I mean, if i set date_min=1, date_max=5, how many day's data am i downloading? 

Thanks a lot.

**Comment by hellock** [comment]
The date arguments are python's `date` object, here is an example.
```python
from datetime import date

google_crawler.crawl('cloudy', max_num=10, date_min=date(2016, 2, 1), date_max=date(2016, 3, 15))
```

**Comment by bryanyzhu** [comment]
@hellock Thanks for your reply. I know it is the `date` object. As in your example, the date is from 02/01/2016 to 03/15/2016. My question is, is 03/15/2016 included? Because in python, sometimes the ending element is excluded. Thanks.

**Comment by hellock** [comment]
Hi @bryanyzhu, this depends on the google image search api. The two arguments are passed to the searching api, which acts the same as searching with web browsers.
![image](https://cloud.githubusercontent.com/assets/9102141/24533483/adc5a5e8-15fa-11e7-82e2-6992006252e7.png)

**Comment by bryanyzhu** [comment]
@hellock oh, I get it. Thanks a lot.
