### ISSUE TITLE
corrupted images after crawling

### ISSUE THREAD

**Issue by outsoo** [hellock/icrawler#21]
Thank you for providing an amazing tool! I'm looking to crawl through some images using the built-in flickr crawler, but after downloading, this is what i see in my directory:
![corrupted](https://cloud.githubusercontent.com/assets/27866690/25295525/73da2ba0-26a9-11e7-921d-560f5c9de394.PNG)

my parameters:
`flickr_crawler.crawl(max_num=100,
    tags='construction',
    user_id='59595815@N03')`

Any ideas?

**Comment by hellock** [comment]
Hi @outsoo ,
I tested the flickr crawler just now and it works well.
This is what it downloaded using the same params as you mentioned above.
![image](https://cloud.githubusercontent.com/assets/9102141/25302088/5dac03d4-2768-11e7-854d-6496f918a879.png)

**Comment by outsoo** [comment]
Im not sure what is causing this issue, but i've resolved it using a virtual environment. It must have just been my machine. Thanks

**Comment by niaoyu** [comment]
@outsoo  
I just meet the same problem. and  figured out the solution by:
in filesystem.py
   mode = 'w' if isinstance(data, str) else 'wb'
   =》
   mode = 'wb'

You may try the solution and check if that works for you :)
