### ISSUE TITLE
Encodeing Error for google crawler

### ISSUE THREAD

**Issue by gajewsk2** [hellock/icrawler#29]
The parser gives me this error when I try to hit this url:
encoding error : input conversion failed due to input error, bytes 0x81 0x95 0xE3 0x82
https://www.google.com/search?q=%E6%92%AE%E5%BD%B1&ijn=0&start=0&tbs=cdr%3A1%2Ccd_min%3A%2Ccd_max%3A%2Csur%3ANone&tbm=isch&lr=lang_ja
That url gets generated by this term: 撮影, manually added the lr parameter for now to force language results, but thats not related to this issue.

Any way to workaround this?

**Comment by hellock** [comment]
Fixed in the latest commit by forcing utf-8 encoding.

**Comment by gajewsk2** [comment]
Thanks for the quick fix on all these issues.
