### ISSUE TITLE
images are sometimes saved with wrong extensions

### ISSUE THREAD

**Issue by indy2018** [hellock/icrawler#30]
Some url's of images doesn't end with '.jpg' or '.png', but there are some additional text with slashes added. When such images are saved in the folder, a couple of subfolders are created. For example:
image with url https://vignette3.wikia.nocookie.net/hotwheels/images/5/5d/Tesla_Model_X_DTX01.png/revision/latest?cb=20170412160359
is saved to folder/000264.png/revision/latest
The file "latest" is a valid image.
Here are more examples of such url's that reproduce the problem:
https://teslamotorsclub.com/tmc/media/solid-black-tesla-model-x-22-inch-wheel-ts115-matte-black-2.116043/full
https://s.yimg.com/uu/api/res/1.2/RTEqzLkvrxNuNROqK4G2OQ--/Zmk9c3RyaW07aD01NjI7cT04MDt3PTEwMDA7c209MTthcHBpZD15dGFjaHlvbg--/http://l.yimg.com/yp/offnetwork/1971a974e71f0dd283dd6e987bb5bcc7

**Comment by hellock** [comment]
Thanks for your report. The bug is now fixed in the latest version.

There exists potential problems. When the extension inference cannot be inferred from the url, the downloader will use 'jpg' as default extension. If the real image is png or gif other than jpg, the downloaded images may be broken.

**Comment by indy2018** [comment]
Thanks for the quick response and the fix.
I confirm that now it is working correctly.
If the extension is missing in the url and the image has different format than the default 'jpg', most image libraries will still be able to load the image, because they use the header in the file to determine the image format. You can use some library like https://docs.python.org/2/library/imghdr.html to check the image format in those cases.
