### ISSUE TITLE
How do I get 1000 images correctly?

### ISSUE THREAD

**Issue by jeffreykira** [hellock/icrawler#38]
I set to download 1000 images, but only download 250~350 images.
How do I get 1000 images correctly?

```
crawler = GoogleImageCrawler(parser_threads=2, downloader_threads=4, storage={'root_dir': TMP_FOLDER})
crawler.crawl(keyword=keyword, max_num=1000, date_min=None, date_max=None)
```

**Comment by hellock** [comment]
Google now seems return less than 1000 images for a searching keyword, as is the same case in the browser. I just tested the keyword `bird` and got about 530 images.

If you want to crawl more images, you can specify different date ranges and crawl more times.
```python
from datetime import date

crawler.crawl('bird', max_num=500, date_min=date(2015, 1, 1), date_max=date(2015, 12, 31))
crawler.crawl('bird', max_num=500, date_min=date(2016,1,1), date_max=date(2016, 12, 31), file_idx_offset='auto')
```
In this way you can get about 990 images, and it can be extended to more.

**Comment by jeffreykira** [comment]
Thank you very much for your reply, it is working now.

**Comment by ryo-matsuzaka** [comment]
Hi, @hellock in this way I could only 65 images...
I have already checked https://github.com/hellock/icrawler/issues/43

```
google_crawler = GoogleImageCrawler(storage={"root_dir": args.data_path}, feeder_threads=2, parser_threads=2, downloader_threads=2)
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2015, 1, 1), (2015, 12, 31))})
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2016, 1, 1), (2016, 12, 31))}, file_idx_offset='auto')
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2017, 1, 1), (2017, 12, 31))}, file_idx_offset='auto')
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2018, 1, 1), (2018, 12, 31))}, file_idx_offset='auto')
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2019, 1, 1), (2019, 12, 31))}, file_idx_offset='auto')
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2020, 1, 1), (2020, 12, 31))}, file_idx_offset='auto')
google_crawler.crawl(keyword="bird", max_num=500, filters={'date': ((2021, 1, 1), (2021, 12, 31))}, file_idx_offset='auto')
```

This is the parts of logs.

> dr%3A1%2Ccd_min%3A01%2F01%2F2018%2Ccd_max%3A12%2F31%2F2018&tbm=isch
> 2022-11-09 14:37:09,519 - INFO - parser - no more page urls for thread parser-002 to parse
> 2022-11-09 14:37:09,520 - INFO - parser - thread parser-002 exit
> 2022-11-09 14:37:10,198 - INFO - parser - no more page urls for thread parser-001 to parse
> 2022-11-09 14:37:10,198 - INFO - parser - thread parser-001 exit
> 2022-11-09 14:37:11,077 - INFO - downloader - no more download task for thread downloader-001
> 2022-11-09 14:37:11,077 - INFO - downloader - thread downloader-001 exit
> 2022-11-09 14:37:11,077 - INFO - downloader - no more download task for thread downloader-002
> 2022-11-09 14:37:11,078 - INFO - downloader - thread downloader-002 exit
> 2022-11-09 14:37:12,062 - INFO - icrawler.crawler - Crawling task done!
> 2022-11-09 14:37:12,062 - INFO - icrawler.crawler - start crawling...
> 2022-11-09 14:37:12,062 - INFO - icrawler.crawler - starting 2 feeder threads...
> 2022-11-09 14:37:12,064 - INFO - feeder - thread feeder-001 exit
> 2022-11-09 14:37:12,066 - INFO - feeder - thread feeder-002 exit
> 2022-11-09 14:37:12,066 - INFO - icrawler.crawler - starting 2 parser threads...
> 2022-11-09 14:37:12,070 - INFO - icrawler.crawler - starting 2 downloader threads...
> 2022-11-09 14:37:12,654 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=0&start=0&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2019%2Ccd_max%3A12%2F31%2F2019&tbm=isch
> 2022-11-09 14:37:12,722 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=1&start=100&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2019%2Ccd_max%3A12%2F31%2F2019&tbm=isch
> 2022-11-09 14:37:13,278 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=2&start=200&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2019%2Ccd_max%3A12%2F31%2F2019&tbm=isch
> 2022-11-09 14:37:13,405 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=3&start=300&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2019%2Ccd_max%3A12%2F31%2F2019&tbm=isch
> 2022-11-09 14:37:13,905 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=4&start=400&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2019%2Ccd_max%3A12%2F31%2F2019&tbm=isch
> 2022-11-09 14:37:15,477 - INFO - parser - no more page urls for thread parser-002 to parse
> 2022-11-09 14:37:15,477 - INFO - parser - thread parser-002 exit
> 2022-11-09 14:37:15,950 - INFO - parser - no more page urls for thread parser-001 to parse
> 2022-11-09 14:37:15,951 - INFO - parser - thread parser-001 exit
> 2022-11-09 14:37:17,097 - INFO - downloader - no more download task for thread downloader-002
> 2022-11-09 14:37:17,097 - INFO - downloader - thread downloader-002 exit
> 2022-11-09 14:37:17,097 - INFO - downloader - no more download task for thread downloader-001
> 2022-11-09 14:37:17,097 - INFO - downloader - thread downloader-001 exit
> 2022-11-09 14:37:18,082 - INFO - icrawler.crawler - Crawling task done!
> 2022-11-09 14:37:18,082 - INFO - icrawler.crawler - start crawling...
> 2022-11-09 14:37:18,082 - INFO - icrawler.crawler - starting 2 feeder threads...
> 2022-11-09 14:37:18,082 - INFO - feeder - thread feeder-001 exit
> 2022-11-09 14:37:18,083 - INFO - feeder - thread feeder-002 exit
> 2022-11-09 14:37:18,083 - INFO - icrawler.crawler - starting 2 parser threads...
> 2022-11-09 14:37:18,084 - INFO - icrawler.crawler - starting 2 downloader threads...
> 2022-11-09 14:37:18,687 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=0&start=0&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2020%2Ccd_max%3A12%2F31%2F2020&tbm=isch
> 2022-11-09 14:37:18,725 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=1&start=100&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2020%2Ccd_max%3A12%2F31%2F2020&tbm=isch
> 2022-11-09 14:37:19,459 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=3&start=300&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2020%2Ccd_max%3A12%2F31%2F2020&tbm=isch
> 2022-11-09 14:37:19,465 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=2&start=200&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2020%2Ccd_max%3A12%2F31%2F2020&tbm=isch
> 2022-11-09 14:37:20,294 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=4&start=400&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2020%2Ccd_max%3A12%2F31%2F2020&tbm=isch
> 2022-11-09 14:37:21,588 - INFO - parser - no more page urls for thread parser-001 to parse
> 2022-11-09 14:37:21,588 - INFO - parser - thread parser-001 exit
> 2022-11-09 14:37:22,345 - INFO - parser - no more page urls for thread parser-002 to parse
> 2022-11-09 14:37:22,345 - INFO - parser - thread parser-002 exit
> 2022-11-09 14:37:23,105 - INFO - downloader - no more download task for thread downloader-002
> 2022-11-09 14:37:23,106 - INFO - downloader - no more download task for thread downloader-001
> 2022-11-09 14:37:23,106 - INFO - downloader - thread downloader-002 exit
> 2022-11-09 14:37:23,106 - INFO - downloader - thread downloader-001 exit
> 2022-11-09 14:37:24,089 - INFO - icrawler.crawler - Crawling task done!
> 2022-11-09 14:37:24,089 - INFO - icrawler.crawler - start crawling...
> 2022-11-09 14:37:24,089 - INFO - icrawler.crawler - starting 2 feeder threads...
> 2022-11-09 14:37:24,090 - INFO - feeder - thread feeder-001 exit
> 2022-11-09 14:37:24,091 - INFO - feeder - thread feeder-002 exit
> 2022-11-09 14:37:24,091 - INFO - icrawler.crawler - starting 2 parser threads...
> 2022-11-09 14:37:24,092 - INFO - icrawler.crawler - starting 2 downloader threads...
> 2022-11-09 14:37:24,726 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=1&start=100&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2021%2Ccd_max%3A12%2F31%2F2021&tbm=isch
> 2022-11-09 14:37:24,800 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=0&start=0&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2021%2Ccd_max%3A12%2F31%2F2021&tbm=isch
> 2022-11-09 14:37:25,425 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=2&start=200&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2021%2Ccd_max%3A12%2F31%2F2021&tbm=isch
> 2022-11-09 14:37:25,541 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=3&start=300&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2021%2Ccd_max%3A12%2F31%2F2021&tbm=isch
> 2022-11-09 14:37:26,028 - INFO - parser - parsing result page https://www.google.com/search?q=bird&ijn=4&start=400&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2021%2Ccd_max%3A12%2F31%2F2021&tbm=isch
> 2022-11-09 14:37:27,635 - INFO - parser - no more page urls for thread parser-001 to parse
> 2022-11-09 14:37:27,635 - INFO - parser - thread parser-001 exit
> 2022-11-09 14:37:28,087 - INFO - parser - no more page urls for thread parser-002 to parse
> 2022-11-09 14:37:28,087 - INFO - parser - thread parser-002 exit
> 2022-11-09 14:37:29,116 - INFO - downloader - no more download task for thread downloader-001
> 2022-11-09 14:37:29,116 - INFO - downloader - thread downloader-001 exit
> 2022-11-09 14:37:29,116 - INFO - downloader - no more download task for thread downloader-002
> 2022-11-09 14:37:29,118 - INFO - downloader - thread downloader-002 exit
> 2022-11-09 14:37:30,100 - INFO - icrawler.crawler - Crawling task done!

**Comment by ZhiyuanChen** [comment]
> Hi, @hellock in this way I could only 65 images... I have already checked #43
> ...

I believe this is rather an issues with Google, see #79.

**Comment by drchristophreuter** [comment]
When searching for images using GoogleImageCrawler, I always get an error message even though I have limited the search to 100 images. Does anyone have a solution for this problem?

Error message:
2023-10-24 15:36:37,554 - INFO - icrawler.crawler - start crawling...
2023-10-24 15:36:37,557 - INFO - icrawler.crawler - starting 1 feeder threads...
2023-10-24 15:36:37,561 - INFO - feeder - thread feeder-001 exit
2023-10-24 15:36:37,561 - INFO - icrawler.crawler - starting 1 parser threads...
2023-10-24 15:36:37,569 - INFO - icrawler.crawler - starting 4 downloader threads...
2023-10-24 15:36:38,158 - INFO - parser - parsing result page https://www.google.com/search?q=cat&ijn=0&start=0&tbs=isz%3Al%2Cic%3Aspecific%2Cisc%3Aorange%2Csur%3Afmc%2Ccdr%3A1%2Ccd_min%3A01%2F01%2F2017%2Ccd_max%3A11%2F30%2F2017&tbm=isch
Exception in thread parser-001:
Traceback (most recent call last):
  File "/home/reuter/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/reuter/anaconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reuter/anaconda3/lib/python3.11/site-packages/icrawler/parser.py", line 94, in worker_exec
    for task in self.parse(response, **kwargs):
TypeError: 'NoneType' object is not iterable
2023-10-24 15:36:42,574 - INFO - downloader - no more download task for thread downloader-001
2023-10-24 15:36:42,575 - INFO - downloader - no more download task for thread downloader-004
2023-10-24 15:36:42,577 - INFO - downloader - thread downloader-004 exit
2023-10-24 15:36:42,576 - INFO - downloader - thread downloader-001 exit
2023-10-24 15:36:42,576 - INFO - downloader - no more download task for thread downloader-003
2023-10-24 15:36:42,582 - INFO - downloader - thread downloader-003 exit
2023-10-24 15:36:42,575 - INFO - downloader - no more download task for thread downloader-002
2023-10-24 15:36:42,584 - INFO - downloader - thread downloader-002 exit
2023-10-24 15:36:43,576 - INFO - icrawler.crawler - Crawling task done!

runfile('/home/reuter/untitled0.py', wdir='/home/reuter')
2023-10-24 15:37:25,544 - INFO - icrawler.crawler - start crawling...
2023-10-24 15:37:25,545 - INFO - icrawler.crawler - starting 1 feeder threads...
2023-10-24 15:37:25,546 - INFO - feeder - thread feeder-001 exit
2023-10-24 15:37:25,546 - INFO - icrawler.crawler - starting 1 parser threads...
2023-10-24 15:37:25,554 - INFO - icrawler.crawler - starting 4 downloader threads...
2023-10-24 15:37:26,032 - INFO - parser - parsing result page https://www.google.com/search?q=cat&ijn=0&start=0&tbs=isz%3Al%2Cic%3Aspecific%2Cisc%3Aorange%2Csur%3Afmc%2Ccdr%3A1%2Ccd_min%3A01%2F01%2F2022%2Ccd_max%3A11%2F30%2F2022&tbm=isch
Exception in thread parser-001:
Traceback (most recent call last):
  File "/home/reuter/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/reuter/anaconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reuter/anaconda3/lib/python3.11/site-packages/icrawler/parser.py", line 94, in worker_exec
    for task in self.parse(response, **kwargs):
TypeError: 'NoneType' object is not iterable
2023-10-24 15:37:30,562 - INFO - downloader - no more download task for thread downloader-001
2023-10-24 15:37:30,563 - INFO - downloader - thread downloader-001 exit
2023-10-24 15:37:30,568 - INFO - downloader - no more download task for thread downloader-002
2023-10-24 15:37:30,571 - INFO - downloader - thread downloader-002 exit
2023-10-24 15:37:30,575 - INFO - downloader - no more download task for thread downloader-003
2023-10-24 15:37:30,576 - INFO - downloader - thread downloader-003 exit
2023-10-24 15:37:30,576 - INFO - downloader - no more download task for thread downloader-004
2023-10-24 15:37:30,579 - INFO - downloader - thread downloader-004 exit
2023-10-24 15:37:31,576 - INFO - icrawler.crawler - Crawling task done!_
