### ISSUE TITLE
Date/Time format

### ISSUE THREAD

**Issue by alphaaurigae** [hellock/icrawler#41]
Cant seem to figure the date/time format for `min_size= `  `max_size= `

**Comment by hellock** [comment]
I'm not very sure what you want to ask, but you may find some examples in [test.py](https://github.com/hellock/icrawler/blob/master/test.py)
```python
google_crawler.crawl(keyword='sunny', max_num=10,
                     date_min=date(2016, 1, 1), date_max=None,
                     min_size=(200,200), max_size=None)
```

**Comment by alphaaurigae** [comment]
that was it i guess `date_min=date(2016, 1, 1) ` may include it in the readme if it isnt yet :)
