### ISSUE TITLE
Is there a way to get the metadata of the images which are being scraped, along with the images?

### ISSUE THREAD

**Issue by kirtanp** [hellock/icrawler#42]
I am interested in the image metadata such as the date, source, etc! Is there some way to get this along with the images?

**Comment by hellock** [comment]
There is not an universal way to obtain image metadata, since crawled images may be compressed by the provider and such information is lost.
For some raw images with metadata, you can read the metadata after downloading the images. Besides, some websites may provide some tags or upload date along the images on the webpage, and this needs specific parsing work for each website.

**Comment by kirtanp** [comment]
I mean just some simple metadata such as image_url, date, image_name, size which you would definitely have while downloading the images

**Comment by hellock** [comment]
These data can be obtained from the `task` dict, you need to rewrite the method `process_meta`. Here is an example. (Please update to the latest version first)

```python
class MyImageDownloader(ImageDownloader):

    def __init__(self, thread_num, signal, session, storage, log_file):
        super(MyDownloader, self).__init__(thread_num, signal, session,
                                           storage)
        self.log_file = open(log_file, 'w')

    def process_meta(self, task):
        if task['success']:
            with self.lock:
                self.log_file.write('{} {} {} {}\n'.format(
                    task['filename'], task['file_url'], *task['img_size']))


crawler = GoogleImageCrawler(
    downloader_cls=MyImageDownloader,
    downloader_threads=4,
    storage={'root_dir': 'images/google'},
    log_level=logging.INFO,
    extra_downloader_args={'log_file': 'meta.txt'})
crawler.crawl('sunny', max_num=10)
```

**Comment by kirtanp** [comment]
Allright, makes sense. Thanks!

**Comment by spencerchubb** [comment]
Is there a way we could get other types of metadata from the task dict also? I would like to be able to get the title, description, and tags.
