### ISSUE TITLE
Adding additional file check before choosing to keep a file?

### ISSUE THREAD

**Issue by tahkion** [hellock/icrawler#46]
Hi! This is a really cool framework and I've been using it for some simple implementations and it has been working great.

Currently, what I'm trying to do is add an additional check of file criteria before the file is saved. I already have this checking code working for offline files already saved, but it's a little long to include here. Maybe for an example, a redundant check of file name/length/size would be work. (Or I can provide the code if it matters!)

The process should be basically this:

1. File is downloaded using icrawler
2. File is checked to meet certain criteria and true/false is returned
3. If the file meets the criteria, it's saved, if not, it's skipped

I've ready the API reference, and I think maybe it can be done by overriding keep_file? But I only see the response/size parameters, and I'm not sure how to add or use my own.

> keep_file
> Parameters: 
> response (Response) – response of requests. min_size (tuple or None)
> minimum size of required images. max_size (tuple or None) – maximum size of required images.

The code example I've been using is this one, and it runs great by itself - I'm just not sure how to initiate that initial check before a file is saved/not saved.

```
from icrawler.builtin import GoogleImageCrawler

google_crawler = GoogleImageCrawler(storage={'root_dir': 'your_image_dir'})
google_crawler.crawl(keyword='cat', max_num=100)

```
Thanks! I'm still new to programming and would really appreciate any help.

**Comment by hellock** [comment]
Yes you can override `keep_file` method. The api in the base class `Downloader` is defined as follows.
```python
def keep_file(self, task, response, **kwargs):
    return True
```
You can check if the file meets some criteria, e.g. the image size, just like what is done in `ImageDownloader` .

**Comment by hellock** [comment]
`keep_file` method is called when an image is to be downloaded. If your want to get the image and check if it meets the criteria, then you can obtain it like this.
```python
def keep_file(self, task, response, **kwargs):
    try:
        # in case that the image is damaged or cannot be downloaded
        img = Image.open(BytesIO(response.content))
    except (IOError, OSError):
        return False
    return perform_test(img, **kwargs)
```

**Comment by tahkion** [comment]
Got it working, thanks!
