### ISSUE TITLE
Add an option to not download in case file already exists

### ISSUE THREAD

**Issue by DreamFlasher** [hellock/icrawler#47]
There is `keep_file` but at that point the file is already downloaded. It would be nice to have an option to skip the download in case a file with that name already exists.

**Comment by DreamFlasher** [comment]
What I had in mind was more about saving time for the download. I do a hash of the URL as filename, so for example if I have to restart the process, or have similar searches that potentially yield the same image, or I want to add the latest files and dont exactly know where I left off, then I don't want to download existing files again to save time.

**Comment by hellock** [comment]
I see your point. It will be really helpful if an option is provided to check the existence of filenames. It would be grateful if you can help to implement this feature, or I will add it later.
