### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by iKaos** [hellock/icrawler#5]
Firstly, I really appreciate your work!

I am currently using this to scrape Google images, but there seems to be an error I can not solve.

`Exception in thread downloader-02:
Traceback (most recent call last):
  File "/home/tn/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/tn/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tn/lib/python3.5/site-packages/icrawler-0.2.1-py3.5.egg/icrawler/downloader.py", line 228, in thread_run
    self.download(task, request_timeout, **kwargs)
  File "/home/tn/lib/python3.5/site-packages/icrawler-0.2.1-py3.5.egg/icrawler/downloader.py", line 124, in download
    img = Image.open(io.BytesIO(response.content))
  File "/home/tn/lib/python3.5/site-packages/Pillow-3.2.0-py3.5-linux-x86_64.egg/PIL/Image.py", line 2309, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x2aaabc453a40>`

Could you assist me with this?

**Comment by hellock** [comment]
Could you show me the parameters you use like the following?
```python
google_crawler = GoogleImageCrawler('images/google', log_level=logging.INFO)
google_crawler.crawl('sunny', 0, 10, date(2016, 2, 1),
                     date(2016, 3, 15), 1, 1, 4, min_size=(200, 200))
```

**Comment by iKaos** [comment]
Yes of course

```python
google_crawler = GoogleImageCrawler(directory)
google_crawler.crawl(keyword = keyword, offset = 0, max_num = max_images,
						 date_min = None, date_max = None, feeder_thr_num=1,
						 parser_thr_num=1, downloader_thr_num=5,
						 min_size=(224,224), max_size=None)
```

**Comment by hellock** [comment]
Hi, this error seems to be caused by the package `Pillow`. When reading the bytes of some images from memory, it will occur occasionally. I currently fix it by catching the exception and skipping the corresponding image.

**Comment by iKaos** [comment]
Hi, I was thinking this also. For now, I modified downloader.py and try catch and continued the while loop when this error occurs.

**Comment by Lightjohn** [comment]
Hello same problem here. There is no clean way to prevent this ? In my case I think we should at least erase the incomplete image. If you want I can try to look a the problem and make a pull request with the solution.

**Comment by Lightjohn** [comment]
Funny thing, it's working perfectly if I set the downloader threads to 1 instead of 4.
And I found another problem: you are forcefully setting extension to .jpg, and on my non windows machine, it's not working. You should at least keep the extension in my opinion.

**Comment by hellock** [comment]
I have tried to solve this problem but no valid answer was found. Some others also complained about the same bug with `Pillow` on stackoverflow. PRs are welcome of course!

**Comment by hellock** [comment]
It's not confirmed if that bug is related to multi-thread because it just occur occasionally during my test cases.
Yeah, there should be an argument to deal with the file extension.

**Comment by tikhop** [comment]
I've been trying to figured out what's happening here and in my case it seems that the image url returns 403 (access denied). For example, the next url "http://suser-upload.cdn-surfline.com/BoLA9bLfQU6do9vC4UaW_praiadotombocam2.jpg" reproduce this issue constantly.
