### ISSUE TITLE
The program does not finish the job

### ISSUE THREAD

**Issue by AndreyVorobey** [hellock/icrawler#7]
The program does not finish the job, at the end of the program I see this,And then I can not do anything.Please help!
![ololo](https://cloud.githubusercontent.com/assets/7907029/16364888/228ec08e-3bfa-11e6-8a4a-9e887f0b3a95.jpg)

**Comment by hellock** [comment]
You can force it to quit using Ctrl-C. I cannot reproduce this bug and need more info to figure it out, could you set the `log_level` to `logging.DEBUG` and run it again?
