### ISSUE TITLE
Cannot download img from google

### ISSUE THREAD

**Issue by rayxuanrayxuanrayxuan** [hellock/icrawler#95]
When I tried to download images from google, it responded with error
"Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f99445e8240>: Failed to establish a new connection: [Errno 101] Network is unreachable"

![image](https://user-images.githubusercontent.com/53335907/109902827-ed892b00-7cd5-11eb-84e5-d693c078d743.png)

But meanwhile I can clone projects from GitHub so I think my proxy works.

Could anyone give some advice on how to fix it？

**Comment by XiaokangLiuCUG** [comment]
Is anyone solves this, I got the same issue.

**Comment by nguyenkaos** [comment]
I got the same issue  today

**Comment by taoyudong** [comment]
Solved the problem and check #102
