### ISSUE TITLE
BingImageCrawler AttributeError: 'HTMLParser' object has no attribute 'unescape

### ISSUE THREAD

**Issue by babanthierry94** [hellock/icrawler#99]
Please, 

I need help to resolve this error when trying to download images with BingImageCrawler.

**Comment by ZhiyuanChen** [comment]
Could you provide a MWE?

**Comment by babanthierry94** [comment]
> Could you provide a MWE?

I don't understand please

**Comment by ZhiyuanChen** [comment]
> > Could you provide a MWE?
> 
> I don't understand please

A Minimum Working Example (MWE) is the minimum code required to reproduce the error.

**Comment by babanthierry94** [comment]
`target_path2 = output_path + "_Bing"
for term in search_terms:
    target_folder = os.path.join(target_path2, "_".join(term.lower().split(" ")))
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    bing_crawler = BingImageCrawler(downloader_threads=4, storage={'root_dir': target_folder})
    bing_crawler.crawl(keyword=term, filters=None, offset=0, max_num=1000)
    time.sleep(SLEEP_BETWEEN_KEYWORDS)`

**Comment by babanthierry94** [comment]
`target_path2 = output_path + "_Bing"
for term in search_terms:
    target_folder = os.path.join(target_path2, "_".join(term.lower().split(" ")))
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)
    bing_crawler = BingImageCrawler(downloader_threads=4, storage={'root_dir': target_folder})
    bing_crawler.crawl(keyword=term, filters=None, offset=0, max_num=1000)
    time.sleep(SLEEP_BETWEEN_KEYWORDS)`

**Comment by babanthierry94** [comment]
> Could you provide a MWE?

```python

target_path2 = output_path + "_Bing"
for term in search_terms:
    target_folder = os.path.join(target_path2, "_".join(term.lower().split(" ")))
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    bing_crawler = BingImageCrawler(downloader_threads=4, storage={'root_dir': target_folder})
    bing_crawler.crawl(keyword=term, filters=None, offset=0, max_num=1000)
    time.sleep(SLEEP_BETWEEN_KEYWORDS)
```

**Comment by babanthierry94** [comment]
in the iCrawler Bing.py file
here is the statement that make error 

_**html_parser.HTMLParser().unescape(div.a['m'])**_

```python
class BingParser(Parser):

    def parse(self, response):
        soup = BeautifulSoup(
            response.content.decode('utf-8', 'ignore'), 'lxml')
        image_divs = soup.find_all('div', class_='imgpt')
        pattern = re.compile(r'murl\":\"(.*?)\.jpg')
        for div in image_divs:
            href_str = html_parser.HTMLParser().unescape(div.a['m'])
            match = pattern.search(href_str)
            if match:
                name = (match.group(1)
                        if six.PY3 else match.group(1).encode('utf-8'))
                img_url = '{}.jpg'.format(name)
                yield dict(file_url=img_url)

```

**Comment by Pxtri2156** [comment]
@babanthierry94  You can try to run on Google Colab. I have run successfully

**Comment by kethan1** [comment]
`unescape` was removed in Python 3.9. It was deprecated before that.
